content/api_en/smooth.xml
=> fixing a typo "open" should be "option" in smooth() documentation

content/examples/Demos/Graphics/Wiggling/Wiggling.pde
Following up on https://github.com/processing/processing/issues/3550
First three commits fix issues:
- begin/endContour() should be called after drawing the main shape
- contours should be drawn counterclockwise, otherwise they won't make a hole
- top and bottom faces were swapped
Last commit simplifies the code by moving face creation and restoration into a separate function and uses rotating faces to their position. If it goes against the purpose of the example, just revert that one.
=> Update wiggling example

content/static/tutorials/arrays/index.html
The following text has been removed from some source code toward the end of the tutorial:
28-24
9236_028.indd 426 10/16/2014 8:
43:
18 PM
PROPERTY OF THE MIT PRESS
FOR PROOFREADING, INDEXING, AND PROMOTIONAL PURPOSES ONLY
427 Arrays
=> Array Tutorial: Remove lingering book annotations from page.

content/static/tutorials/drawing/imgs/drawing-03.svg
The SVG image showing 'Eighth Grade' coordinates had the x at the top and the y on the right. This fixes it.
Offending image is here:
https://processing.org/tutorials/drawing/imgs/drawing-03.svg
From this tutorial:
https://processing.org/tutorials/drawing/
=> Typo fix on coordinate system tutorial... x and y axes text on 'Eighth Grade' coordinate example

content/api_en/PImage_loadPixels.xml, content/api_en/PImage_pixels.xml, content/api_en/loadPixels.xml, content/api_en/pixels.xml
I don't think the docs were clear enough on the fact that `loadPixels()` stores a *snapshot* of the display in `pixels[]` (rather than opening a handle). [It tripped me up anyways.](https://forum.processing.org/two/discussion/15939/why-does-background-not-clear-the-display-here#latest)
I tried to make that clearer, and made some other wording changes while I was there.
=> Changes to the reference docs for pixels[] and some related functions

java_generate/templates/class.template.html, java_generate/templates/generic.template.html, templates/foundation-template.reference.item.html, templates/template.reference.item.html
Should make browsers so happy that they would on most reference pages display green lock instead of "parts of this webpage are not secure".
Current insecure links redirect on their own to the secure links I used, so nothing should change.
=> Replace links to CC banner with secure version

content/static/tutorials/p3d/index.html
Fix example code in p3d tutorial that does not work as expected after changes in `ortho()` (processing/processing#1278).
=> Ortho example in p3d tutorial is broken

content/examples/Demos/Graphics/MeshTweening/data/vert.glsl
On the Raspberry Pi's GLES2 driver, this failed with: ERROR:SEMANTIC-4 (vertex shader, line 12) Operator not supported for operand types
=> Fix MeshTweening vertex shader (#523)

content/examples/Topics/Shaders/DomeProjection/DomeProjection.pde
The initCubeMap function does not work on GLES2 at least:
````
glGetError() returned the following error codes after a call to glTexParameteri(<int> 0x8513, <int> 0x8072, <int> 0x812F): GL_INVALID_ENUM ( 1280 0x500)
glGetError() returned the following error codes after a call to glTexImage2D(<int> 0x8515, <int> 0x0, <int> 0x8058, <int> 0x400, <int> 0x400, <int> 0x0, <int> 0x1908, <int> 0x1401, <java.nio.Buffer> null): GL_INVALID_VALUE ( 1281 0x501)
````
=> Document Topics/Shaders/DomeProjection caveat

content/examples/Basics/Form/PieChart/PieChart.pde
pieChart function uses a mix of its argument (data[]) and the original global array (angles[]). Fixed so it uses only the argument.
see discussion:
https://forum.processing.org/two/discussion/17771/flaw-in-processing-org-website-piechart-example
=> PieChart.pde function fix - use argument

content/api_en/loadStrings.xml
Processing documentation and code uses the style: `String[] arrayName=`.
This is the only example I've seen that uses the compiler-equivalent `String arrayName[]=` declaration style. It is correct, but potentially confusing to new programmers -- especially because it the example doesn't obviously match the return type listed under Returns.
Changed to String[] style.
=> Change array style to match other examples

content/static/download.html, download/install-arm.sh
This should go in once https://github.com/processing/processing/pull/5002 lands in a released version.
(At that point, content/static/download.html will also want to be updated to include the download link to the "ARM64" version.)
=> Add 64-bit ARM detection to install-arm script

content/static/tutorials/video/index.html
Fixes typos and bugs in the video tutorial, including the one reported in #549 
Fixes include:
- Newlines between comments and code
- Missing video.start() in colored cell example
- Index out of range in colored sketch example
=> Typo and bug fixes in video tutorial

content/examples/Basics/Math/Sine/Sine.pde
The `Basics/Math/Sine` example was calling `noStroke` twice.
=> Remove redundant call to noStroke

content/api_en/createShape.xml
The list of functions corresponding to PShape parameters did not include `quad()`. It appeared to be an oversight and this corrects it.
=> Add quad() to corresponding functions in PShape

content/static/tutorials/eclipse/index.html
Since exporting in Eclipse isn't unique with processing, seemed best to just link to Eclipse's documentation.
=> Add a line about exporting in Eclipse

content/api_en/LIB_svg/index.html, content/api_en/libraries/index.html, generate/libraries.php, generate/libraries_local.php
addresses issue #406.
Sample code in the Library page is included in the following repo: https://github.com/quinkennedy/processing-svg-examples
=> Added library page for SVG modeled after PDF page.

content/examples/Basics/Input/MouseSignals/MouseSignals.pde
The mouseX signal is not properly drawn on the graph, xvals[i] is simply divided by 3 like in the case for mouseY, which is not the case, but instead, it should be mapped from "width" to "height/3" .
Hence the line 49: point(i, map(xvals[i],0,width,0,height/3-1));
=> Rectifying graph for mouseX signal

content/api_en/unbinary.xml
Documentation for unbinary PR processing/processing#5681
Accepts an integer that uses decimal format to represent a sequence of bits, and returns an integer in native format.
For example, the integer 1101 represents binary, and returns 13 (binary 0b1101, or 8+4+0+1 = 13). 
This signature extends unbinary(String value). It is a workaround for lack of parser support for binary literals such as 0b1101.
=> Add unbinary int signature

content/examples/Basics/Color/RadialGradient/RadialGradient.pde, content/examples_p5/Basics/Color/RadialGradient/RadialGradient.js
Typo in a comment in RadialGradient that shows on the documentation page. Bug also found in p5js code even though it doesn't show up in the documentation on the web.
Fix for issue #722
=> Fix typo in RadialGradient documentation page

content/static/tutorials/electronics/imgs/fg39-16.svg, content/static/tutorials/electronics/index.html
=> Fixed example 4 for the Electronics Tutorial

content/static/tutorials/electronics/index.html
changed the "<" and ">" characters for their HTML entities. Related to #496
=> fixed encoding of character on sketch 4A of electronics tutorial

content/api_en/unbinary.xml
This reverts commit 1b00fd0194087d195929aafbe37c50a011cd6b4a.
That docs PR was tied to a Processing PR to add an unbinary signature -- https://github.com/processing/processing/pull/5681.
The docs update was accepted, but the Processing PR is still open, so the docs describe a feature that wasn't added. This could be reapplied again if that feature is ever added to the language and released, but should be reverted for now.
=> Revert "Add unbinary int signature"

content/examples/Basics/Color/Brightness/Brightness.pde
**Issue**
The colors in the color brightness example always seem to be rather dark. Even when moving the cursor to the lowest position possible.
**Reason**
The maximum value for brightness is being set to the `width` of the canvas. As `mouseY` is being used as the brightness of the color and the height of the canvas is much lower than the width, it is impossible to reach full brightness for a bar.
**Fix**
This can be fixed by setting the maximum value for brightness to the `height` of the canvas.
=> Brightness example: Fix maximum value for brightness

content/api_en/nf.xml
Adds documentation for a common nf use case -- setting left to 0 and formatting the right-hand side only to some decimal precision. Adds examples (tested) and modifies incorrect language in the reference summary to indicate that left=0 is valid.
closes #774
=> Update nf to show right-hand formatting examples

contrib_generate/sources.conf
Adds the PDE Processing Rosetta Code example set to Contributions Manager.
https://github.com/jeremydouglass/processing_rosetta_examples
=> Add Rosetta Code example set

content/api_en/point.xml, content/api_en/strokeCap.xml
=> Document strokeCap setting for square points, invisible points problem

content/api_en/include/doccomment.xml, content/api_en/include/multilinecomment.xml
and adds line on how to do javadoc generation with third-party tools.
closes #796
=> doccomment drops outdated ref to index.html generation

content/api_en/point.xml, content/api_en/strokeWeight.xml
As per Ben Fry suggestion:
https://github.com/processing/processing/issues/5957#issuecomment-575353739
> Using point() with small strokeWeight(1) or smaller may not draw anything to the screen, depending on the graphics settings on your computer. To fix this, you can 1) use set() instead, 2) use a larger strokeWeight(), or 3) draw the point using circle() or square() instead.
=> Document strokeWeight(1) + invisible point() problem, workarounds

content/static/tutorials/sound/index.html
Link to tutorial sketches to related examples sketches that contain required mp3s.
=> Sound Tutorial - ex3-6 link sketches w/required MP3s, closes #714

contrib_generate/sources.conf
@prisonerjohn I'm working on releasing a new version of the HTTPRequests-for-Processing library and I think it makes more sense to point to the "latest" tag on github? Is this the correct way to do so? cc @runemadsen
=> HTTPRequests Library download URL change
